# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d6b6d73f8238775593958d4840b7782f2f954803342b36f5b7575526d800e50c2717441dbf8c4502beb4f26f87521f393c2fa574cc61c5e425ad4e7c5f6837a

test:
  secret_key_base: caf524a986861c7c1c8f1ce75143ac785150cd1a800b1962df8d1ddc04c2e92d7580391316b7d5a95a1a97b9c42ab20114b3c8378cd96f5b6ef367918acea863

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
